##########################EKS#################

output "kubectl_config" {
  description = "kubectl config as generated by the module."
  value       = module.eks.kubeconfig
}

output "config_map_aws_auth" {
  description = "A kubernetes configuration to authenticate to this EKS cluster."
  value       = module.eks.config_map_aws_auth
}

output workers_asg_names {
  value = module.eks.workers_asg_names

}

#######################SCHEDULE####################
output "aws_autoscaling_schedule_start" {
  value = "${module.SCHEDULE.aws_autoscaling_schedule_start}"
}

output "aws_autoscaling_schedule_stop" {
  value = "${module.SCHEDULE.aws_autoscaling_schedule_stop}"
}
#######################SG#######################
output NAME-AUTOSCALING {
  value = module.eks.NAME-AUTOSCALING
}
